name: Build Run and Test Website Crawl

on:
  workflow_dispatch:
    inputs:
      A11Y_SCAN_URL:
        description: 'https://www.amazon.fr/'     
        required: true
        default: 'https://www.amazon.fr/'
      A11Y_SCANNER:
        description: 'Scanner (website, sitemap)'     
        required: true
        default: 'website'
      A11Y_SCAN_MAX_NUM_PAGES:
        description: 'Maximum Number of Pages to Scan'     
        required: true
        default: '10'
      A11Y_SCAN_MAX_CONCURRENCY:
        description: 'Maximum Number of Concurrent Page Scans'     
        required: true
        default: '10'
      A11Y_SCAN_SCREENSHOTS:
        description: 'Include screenshots (screenshots, none)'     
        required: true
        default: 'screenshots'
      A11Y_SCAN_FOLLOW_ROBOTS:
        description: 'Crawler adhere to robots.txt (yes, no)'     
        required: true
        default: 'no'
        
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        repository: GovTechSG/purple-a11y
    
    - name: Build and run Docker container
      run: |
        # Build your Docker image (replace 'purple-hats' and 'Dockerfile' with your image name and Dockerfile path)
        docker build -t purple-hats .
        # Run the Docker container (adjust any options as needed)
        docker run -dit --name purple-hats-container purple-hats
      # Ensure the Docker container is running before running the next step
      continue-on-error: true

    - name: Run Node CLI command inside the Docker container
      run: |
        # Execute a webisite crawl
        docker exec purple-hats-container node cli -c "${{ github.event.inputs.A11Y_SCANNER }}" -u "${{ github.event.inputs.A11Y_SCAN_URL }}" -p "${{ github.event.inputs.A11Y_SCAN_MAX_NUM_PAGES }}" -t "${{ github.event.inputs.A11Y_SCAN_MAX_CONCURRENCY }}" -a "${{ github.event.inputs.A11Y_SCAN_SCREENSHOTS }}" -r "${{ github.event.inputs.A11Y_SCAN_FOLLOW_ROBOTS }}" -k "${{ github.actor }}:${{ github.actor }}@users.noreply.github.com" -b chromium || true
       
    - name: Print errors
      run: |
        docker exec purple-hats-container cat errors.txt || true
      
    - name: Print logs
      run: |
        docker exec purple-hats-container cat logs/*/*.txt || true
    - name: Copy Results from Docker Container
      run: docker cp purple-hats-container:/app/results ./results

    - name: Zip Results
      run: zip -r results.zip ./results

    - name: Upload Zip File
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: results.zip
          
    - name: Cleanup Docker container
      run: |
        # Stop and remove the Docker container
        docker stop purple-hats-container
        docker rm purple-hats-container
